templates/cinder/config/httpd.conf

The current WSGI VirtualHost for Cinder API is a big dirty.
We have the same VirtualHost configuration in 2 files, `10-cinder_wsgi.conf` and `httpd.conf` which makes it hard to know which one is actually being used.
The reason why it's duplicated is because we currently have the inclusion of the whole `conf.d` directory where `10-cinder_wsgi.conf` resides commented to disable SSL.
This patch cleans this up a bit and makes sure that we only have the VirtualHost configured in one place, `10-cinder_wsgi.conf` and we either include the configuration files from `conf.d` file or explicitly the Cinder wsgi configuration.
This removes confusion.

Cleanup httpd.conf

---

controllers/cinder_controller.go

Failures during the rendering and creation of the Config Maps are being ignored.
This patch changes this behavior and make generation failures prevent the operator from advancing in the process of deploying Cinder, after all without the Config Maps the services will not run as expected or not run at all.

Fix ConfigMap generation ignores failures

---

pkg/cinderapi/deployment.go
pkg/cinderbackup/statefulset.go
pkg/cinderscheduler/statefulset.go
pkg/cindervolume/statefulset.go

The operator will fail to deploy Cinder volume, backup, and scheduler containers when the Service is set to debug mode:
debug:
service: true
This is because the startup probe will be missing an execution command.
In this patch we simply add the same dummy check for the startup probe as we do in the liveness and readiness probes and make a small change in the different probe exec setting to use the same instance for all probes instead of creating different instances with the same contents for each probe.

Fix debug mode

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

Most of the logging in the Cinder operator don't show the name of the Cinder CR instance that is being worked on.
This patch simply adds the name to all the logs.

Log the Cinder CR instance name

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go

When updating to the latest keystone-operator API on commit 57dfebea4265254cd44b3cb87e27048902ddd460 we unified the assigned package name as "keystone", which diverges from what other openstack operators are doing.
This patch renames all instances to "keystonev1" to be consistent with the other operators.

Rename keystone package name to keystonev1

---

pkg/cinderbackup/statefulset.go
templates/cinder/config/cinder-backup-config.json

This PR fixes a couple of things in the cinder-backup services:
- Fixes the support for the Ceph Backup driver (currently doesn't have the required files).
- Make the cinder-backup container privileged.

Fix backups

---

templates/cinder/config/cinder.conf

Our current cinder.conf template hardcodes the Glance server, which means that operators will need to set this manually.
This patch changes this to use the Keystone catalog instead, telling cinder to check for Glance's internal endpoint to get the actual address.
This seems like a sane default, because even if it is slower due to the additional request to keystone, it has the benefit of always working and automatically adapting to any changes.
In the future we could make the operator set the glance_api_servers itself checking the OpenShift service and then add a watcher to it so it can react if it were to change.
That would give users the best of both worlds, speed and automatic updates of cinder.conf on changes.

Use keystone catalog info for Glance

---

pkg/cinderbackup/statefulset.go
pkg/cindervolume/statefulset.go

This patch reduces memory usage on the Cinder Volume and Backup services by tuning glibc.
The specific tuning consist on disabling the per thread arenas and disabling dynamic thresholds.
The Cinder Backup service suffers from high water mark memory usage and uses excessive memory.  As an example just after 10 restore operations the service uses almost 1GB of RAM and does not ever free it afterwards. With this patch the memory consumption of the service is reduced down to almost 130MB and memory consumption during runtime is also halved.
This patch is the equivalent to OpenStack patches:
- DevStack: https://review.opendev.org/c/openstack/devstack/+/845805
- TripleO: https://review.opendev.org/c/openstack/tripleo-common/+/845807
Information on glibc tuning is available at: …

Reduce memory consumption in Cinder services

---

templates/cinder/config/cinder.conf

On commit a6aaee5063adb533226d8e2a25b742c42ebdd158 we intended to change the way we get the Glance server addresses from using a hardcoded address to using the Keystone internal Glance URL catalog entry, but due to a mistake the service is using the public one instead (default when value not defined).
This patch fixes this and Cinder will use the intended internal URL instead.
This fixes the mistake from https://github.com/openstack-k8s-operators/cinder-operator/pull/32

Using internal Glance URL

---

.github/workflows/build-cinder-operator.yaml

Only required if we are converting image tags to shas and reference registry.redhat.io images.

Drop registry.redhat.io login from github action

---

Makefile
api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml

With the new api sub module, consumer operators just have to import the api submodule. For envtest it is required to install CRD for e.g. keystone-operator and mariadb-operator to be able to use it.
Moving the directory config/crd/bases which holds the generated files in to the api module that they are available with the module and link the dir in the original place does not work as kustomize autodetect fails on symlinked directories [1].
This updates the `generate` Makefile target to copy config/crd/bases to /api on successful generation run.
[1] kubernetes-sigs/kustomize#1886

Copy rendered CRD files dir to /api/bases in make manifests

---

.github/create_bundle.sh

This would no longer get triggered as our default Makefile image is now set to a fully qualified URL (quay.io....)

Drop controller:latest logic from create_bundle.sh

---

pkg/cinder/dbsync.go
pkg/cinder/volumes.go
pkg/cinderapi/volumes.go
pkg/cinderbackup/volumes.go
pkg/cinderscheduler/volumes.go
pkg/cindervolume/volumes.go
templates/cinder/config/cinder.conf

os-brick file locks need to be shared across all the OpenStack services
that use os-brick and are running on the same host, if we don't there
will be race conditions that make attach/detach operation unexpectedly
fail.
Services that need to share this locks location are cinder-volume,
cinder-backup, and glance when using cinder as a backend.  Nova compute
would also need to share them in an HCI environment, but that won't be
the case here because nova-compute won't be running in OpenShift.
This patch uses the host's `/var/locks` directory to share these locks.
In OSP17 there is a single lock path configuration option for cinder and
os-brick locks, but in OSP18 there is an os-brick specific configuration
option that can be used.
To make the operator compatible with OSP17 and OSP18 …

Share os-brick locks between OpenStack services

---

templates/cinder/config/cinder.conf

The cinder-scheduler service is getting restarted when the cinder-volume service is not started within 1 minute of the service start.
The reason why this is happening is that the scheduler service does a heartbeat on start, which makes the service appear as up for the next 60 seconds to OpenStack and our healthcheck.py service, and thus makes the startup probe consider the service is successfully running for those 60 seconds.
But because there is no cinder-volume service sending capability reports, the scheduler decides to wait for 60 seconds for one not doing anything but waiting, so no heartbeats are sent.
This means that the scheduler will appear first as UP, then as DOWN for some seconds, and then as UP again, but if the probe checks just as the service is down it will restart the …

Fix scheduler restart

---

api/bases/cinder.openstack.org_cinders.yaml
api/v1beta1/cinder_types.go
config/crd/bases/cinder.openstack.org_cinders.yaml

`oc get cinder` will now surface the status (following the pattern used by other operators)

Show overall Cinder status in CLI

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
api/v1beta1/common_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml

When a CRD has an optional struct field the defaulting of that field needs special care. Both the field with the struct type need a full default value defined and each individual subfields in the struct needs default value defined. Otherwise in the first reconcile call the PasswordSelectors is empty and then in the second reconcile it is filled.
Now documented via https://github.com/openstack-k8s-operators/docs/pull/12

Fix defaulting PasswordSelectors

---

pkg/cinder/dbsync.go

When `dbsync` is called, both `Volumes` and `VolumeMounts` are defined in the `DbSyncJob` function (using the very same parameters). 
This change just removes the duplicated line that calls the same function.
Signed-off-by: Francesco Pantano <fpantano@redhat.com>

Remove useless GetVolumes call

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml
controllers/cinder_controller.go

This change adds the top level NodeSelecter to the Cinder CR.  This can then be overridden by individual CR's as required.

Add top level NodeSelector to Cinder CR

---

controllers/cinder_controller.go
go.mod
go.sum

add_service_db_finalizer_logic
Ever since  : https://github.com/openstack-k8s-operators/lib-common/pull/87
Podified operators which use service dbs and the db.CreateOrPatchDB method ,
now will get the finalizer set on the db automatically when using the newest lib-common, 
but they won't have the code remove it on cleanup i.e reconcileDelete,
which might make the delete operator action hang.
This adds the service Db removal code in the operator delete (reconcileDelete)
function to work with the above.
Also updated lib-common to latest as to not break lib-common's exported functions

add service db finalizer logic

---

controllers/cinderapi_controller.go
pkg/cinder/const.go

Remove the cinderv2 keystone service and endpoints. Cinder's APIv2 was removed in Xena.
The cinderv3 endpoints are updated to remove the project_id from the API URLs. Cinder no longer requires a project_id in the URL as of the Yoga release.
NOTE: This patch does not remove stale cinderv2 artifacts from an existing deployment. Due to another issue with the finalizers (to be addressed separately), the following commands can be executed to remove the v2 service and endpoints:
$ oc patch keystoneservice/cinderv2 --type json \
--patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
$ oc delete keystoneservice/cinderv2
$ oc patch keystoneendpoints/cinderv2 --type json \
--patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
$ oc delete keystoneendpoints/cinderv2

Fix keystone services and endpoints

---

controllers/cinder_controller.go
templates/cinder/config/cinder.conf

Internal endpoint is meant for interaction between services. This ensures cinder uses internal endpoints when it sends requests to the other services.

Use internal endpoint to interact with Keystone/Nova

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

The current logic ignores the error but it should be returned so that the error can be detected in the reconciler.

Return error in ConfigMap creation

---

.github/workflows/build-cinder-operator.yaml

We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.

Drop paths-ignore from build operator workflow

---

.github/workflows/build-cinder-operator.yaml

We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145

Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/common_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml

Otherwise marshalling/unmarshalling CRDs with webhooks results in error as it serializes these slice fields as "null".
The KeystoneAPI "keystone" is invalid: spec.networkAttachmentDefinitions:
Invalid value: "null": spec.networkAttachmentDefinitions in body must be
of type array: "null"

Add omitempty tag for slices

---

templates/cinder/bin/init.sh
templates/cinder/config/cinder.conf

... instead of nova user. This allows us to reduce dependency on the resources managed by nova-operator and better separate each operators. The credential should work fine as long as the user has admin access with the 'service' project scope.

Use own user to send admin requests to nova

---

api/v1beta1/cinder_types.go

deploy openstackcontrolplane without cinder specified fails right now with:
spec.cinder.template.cinderVolumes: Invalid value: "null": spec.cinder.template.cinderVolumes in body must be of type object: "null"

Add omitempty to CinderVolumeSpec

---

Makefile
api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml

This patch rebuilds the Cinder `CRD` removing the description to avoid a potential issue when the cinder bundle is deployed via `OLM` by the meta operator and the following is seen:
```
openstack/install-7ws9s"} failed: failed to update installplan bundle lookups: etcdserver: request is too large
```

Remove description from Cinder CRD

---

pkg/cinder/dbsync.go

... instead hard-coding the string in our own logic.

Use constant to define restart policy

---

Makefile
api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
api/v1beta1/common_types.go
config/certmanager/kustomizeconfig.yaml
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml

* 0.2.1: The fixed finding is about mixing Required and omitempty in the same field def. See https://github.com/gibizer/operator-lint/tree/main/linters/crd/C002 . Note that this makes the Secret and the DatabaseInstance fields properly required.
* 0.3.0: Having a CRD field with omitempty tag with a kubebuilder default value defined can cause unexpected behavior.
See https://github.com/gibizer/operator-lint/blob/main/linters/crd/C003 for details.

Bump operator-lint to 0.3.0 and fix findings

---

Makefile
hack/configure_local_webhook.sh

Allows webhooks to run locally for dev/test via `make run-with-webhook`

Support local webhooks

---

controllers/cindervolume_controller.go

The CR for cinder-volume services describe the backends, which are expected to be listed in the [DEFAULT]/enabled_backends. In order to make things easier on the cloud admin, the cinder-operator can now infer the enabled_backends by scanning the customServiceConfig that defines the backends.
If the customServiceConfig does specify the enabled_backends, then that value is honored. The enabled_backends is inferred only if it's not specified in the CR.
Note that this is not equivalent to a transforming or defaulting webhook, because the CR is not affected. It only affects the final settings in the generated cinder.conf.

Infer enabled_backends if it's not specified in the CR

---

config/samples/backends/nfs/backend.yaml
config/samples/backends/nfs/cinder-volume-nfs-secrets.yaml
config/samples/backends/nfs/kustomization.yaml

This config sample shows how to deploy an NFS backend, with sensitive settings (the nas_host and nas_share_path) stored in a Secret referenced in the backend's customServiceConfigSecrets.

Add NFS backend config sample

---

config/samples/backends/lvm-iscsi/backend.yaml
config/samples/backends/lvm-iscsi/iscsid.yaml
config/samples/backends/lvm-iscsi/kustomization.yaml
config/samples/backends/lvm-iscsi/lvm.yaml
config/samples/backends/lvm-iscsi/multipathd.yaml
pkg/cinder/volumes.go
pkg/cinderbackup/statefulset.go
pkg/cindervolume/statefulset.go
templates/cinder/bin/run-on-host
templates/cinder/config/cinder-backup-config.json
templates/cinder/config/cinder-volume-config.json

Fix iSCSI and multipathd on cinder volume and backup pods.
To allow testing it we also fix the LVM driver and provide a simple mechanism to run this backend on CRC.
In OpenShift the approach is to have iscsid and multipathd running on the host and using `nsenter` inside the container to communicate with them.
Commit messages have additional information.

Fix iscsi lvm

---

config/manifests/bases/cinder-operator.clusterserviceversion.yaml

This updates the keywords of cinder CRD so that the items are more consistent with the other operators.

Use consistent words for keywords

---

config/samples/backends/lvm-iscsi/backend.yaml
templates/cinder/bin/init.sh
templates/cinder/config/cinder.conf

- Add [backend_defaults] and set use_multipath_for_image_xfer True
- Configure the [service_user] section
- Minor cleanup: removed obsolete comments, and sort the sections alphabetically. The sorting isn't critcal, but I didn't like seeing the oslo sections scattered all over the place.

Enhancements to default cinder.conf

---

api/go.mod
api/go.sum

This patch removes the leftover replacement of the lib-common library in the api sub module.

Remove leftover api sub module

---

pkg/cinderapi/deployment.go
tests/kuttl/common/assert_sample_deployment.yaml

Use instance.Name so that "-api" will appear in the pod name. Now c-api pods will be named like this:
cinder-api-58ccfdc568-6lg6m
whereas they previously looked like this:
cinder-58ccfdc568-6lg6m

Fix cinder-api pod name

---

tests/kuttl/tests/cinder_scale/01-deploy-cinder.yaml
tests/kuttl/tests/cinder_scale/05-cleanup-cinder.yaml
tests/kuttl/tests/cinder_scale/deploy/kustomization.yaml

Instead of using install_yamls targets for deploying and cleaning up
cinder, use the CR sample from config/samples. This removes a possible
circular dependency issue when using install_yamls to run the jobs and
to run some test steps.

Remove install_yamls dependency for kuttl tests

---

Makefile
README.md
config/default/manager_default_images.yaml
config/samples/cinder_v1beta1_cinder.yaml
tests/kuttl/common/assert_sample_deployment.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

pkg/cinder/const.go

The constant has not been used since we stopped creating admin endpoint.

Remove unused constant for admin endpoint

---

pkg/cinderbackup/volumes.go

A previous patch created the appropriate volume so that cinder-backup has access to /var/lib/cinder, but it neglected to mount the volume.

Add cinder-backup mount for /var/lib/cinder

---

config/manifests/bases/cinder-operator.clusterserviceversion.yaml

This should hide the cinder package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

CSV: Set operator-type: non-standalone

---

config/samples/backends/bases/openstack/openstack.yaml

This realigns the sample config with changes made to other service's CRD, namely OVS/OVN networking.

Refresh "openstack" backend base sample config

---

.github/workflows/build-cinder-operator.yaml

When we switched from `master` to `main` as the default branch name, we forgot to update the GitHub workflow scripts for automated builds.  We've been mistakenly building `main-latest` instead of `latest` for the past two months.  This was at least causing `install_yamls` to use the outdated version since then.

Fix 'latest' tag used in GitHub automated builds

---

config/samples/backends/bases/openstack/openstack.yaml
controllers/cinder_controller.go

Many OpenStack deployments do not use the cinder-backup service. With this in mind, the service should not be deployed unless the number of replicas is greater than zero. Conversely, the deployment should be cleaned up (deleted) if the service is scaled down to zero replicas.

Make deploying cinder-backup optional

---

templates/cinder/config/00-config.conf

The default for cinder volume service is to enable multipathing, but we are missing this on the backup service.
This patch enables multipathing by default for backup services as well.

Backup: Enable multipathing by default

---

config/samples/backends/bases/multipathd/multipathd.yaml

This patch updates the multipath sample configuration to set the "recheck_wwid" value to "yes".
This aligns with what we are recommending in the adoption documentation for the Cinder service.

Backend Sample: Update multipath configuration

---

controllers/cinder_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

kuttl-test.yaml
tests/kuttl/common/assert_sample_deployment.yaml
tests/kuttl/tests/cinder_scale/01-deploy-cinder.yaml
tests/kuttl/tests/cinder_scale/05-cleanup-cinder.yaml
tests/kuttl/tests/cinder_scale/05-errors.yaml
tests/kuttl/tests/cinder_scale/deploy/kustomization.yaml

Modify the kuttl tests so that they can run in any namespace, not just
in the openstack one. This requires removing any mention of the
namespace in the asserts and using the $NAMESPACE variable in scripts
instead of the namespace name.
Needs https://github.com/openstack-k8s-operators/install_yamls/pull/410 to be
merged for CI to pass.

Change kuttl tests to run in any namespace

---

templates/cinder/config/00-config.conf

Due to a bug in the cinder backup service [1] the service may appear to be down when doing multiple concurrent operations.
When the service appears as down the probe will detect it and will end up restarting the service, which aborts all the ongoing operations.
While the bug is getting fixed we increase the service_down_time to 3 minutes. This is not ideal because it also affects the cinder volume service, but it also prevents human operators from seeing the false down state.
The alternative would be to change the probing configuration just for the backup service.
[1]: https://bugs.launchpad.net/cinder/+bug/2026877

Fix Backup getting restarted

---

pkg/cinder/dbsync.go
templates/cinder/config/db-sync-config.json

When adopting the cinder services we end up with the services getting pinned to the old RPC and OVO versions, and to fix that we would need to restart the services.  This is the standard rolling upgrades mechanism.
Since the adoption is more like an offline update/upgrade we need to bump these versions in the DB before we start them so they all start with the right versions.
The `cinder-manage db sync` command has a flag specifically designed for this purpose: `--bump-versions`
This patch adds this flag to the job that syncs the DB.
Once we start working on updates and upgrades we'll have to revisit this to see if we need to tweak it or not.

DBSync: Bump service versions

---

api/v1beta1/conditions.go
controllers/cinder_controller.go

We have added the common RabbitMqTransportURLReady to lib-common to reduce duplicate implementations.
Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/300

Replace RabbitMqTransportURLReady by common condition

---

pkg/cinder/const.go
pkg/cinder/dbsync.go
pkg/cinderapi/const.go
pkg/cinderapi/deployment.go
pkg/cinderapi/volumes.go
pkg/cinderbackup/const.go
pkg/cinderbackup/statefulset.go
pkg/cinderbackup/volumes.go
pkg/cinderscheduler/const.go
pkg/cinderscheduler/statefulset.go
pkg/cinderscheduler/volumes.go
pkg/cindervolume/const.go
pkg/cindervolume/statefulset.go
pkg/cindervolume/volumes.go
tests/kuttl/common/assert_sample_deployment.yaml

Use a volume mount instead of overriding KOLLA_CONFIG_FILE for each service.

Stop using KOLLA_CONFIG_FILE environment variable

---

pkg/cinder/volumes.go
pkg/cinderapi/deployment.go
pkg/cinderapi/volumes.go
pkg/cinderbackup/statefulset.go
pkg/cinderbackup/volumes.go
pkg/cinderscheduler/statefulset.go
pkg/cinderscheduler/volumes.go
pkg/cindervolume/statefulset.go
pkg/cindervolume/volumes.go

The unused "secretNames" arg is removed from several GetVolumes() functions. Its need was eliminated when the config process was overhauled to not use init containers.
For the cinder-backup and cinder-volume versions of the function, two volumes and their mounts were moved to the top level cinder.GetVolumes() and GetVolumeMounts() functions, which already has specific support for those services.

Clean up GetVolumes() functions

---

controllers/cinderapi_controller.go
pkg/cinder/const.go
pkg/cinderapi/const.go
pkg/cinderapi/deployment.go
pkg/cinderapi/volumes.go
templates/cinder/config/00-config.conf
templates/cinderapi/config/01-config.conf
templates/cinderbackup/config/01-config.conf
templates/cindervolume/config/01-config.conf

Add support for a new service specific config snippet, which is loaded after the global snippet and before the "custom" global snippet supplied by the user. This adds the ability for the operator to override certain global settings on a per-service basis.
The immediate use case is to provide a cleaner way to override the logging configuration for the cinder-api service.
The [backend_defaults] section in the global snippet has been moved into a new cinder-volume service specific snippet.

Support service specific config snippets

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml

These spec fields are required to deploy cinder services.
Although we currently do not intend to support direct usage of sub CRs, requiring these fields allows us to catch any bug in cinder controller.

 Require databaseHostname and transportURLSecret

---

templates/cinder/config/00-config.conf

This patch updates the global defaults in `00-config.conf` to:
- Check service token roles in the KeyStone middleware.
- Allow cloning of Glance image volumes when Glance is using Cinder as a backend.

Update cinder.conf defaults

---

controllers/cindervolume_controller.go
pkg/cindervolume/const.go

When we deploy multiple cinder volume backends with network attachments the reconciliation loop is constantly getting called.
This issue happens because each of the cindervolume objects ends up with the IP addresses of the network attachments of all the different backends as the labels that these services are the same.
This patch adds a new label with the backend name so that the network attachments are not merged.
Before the patch we would see both IP Addresses:
```
NAME                         NETWORKATTACHMENTS                                                                                  STATUS   MESSAGE
cinder-volume-lvm-iscsi      {"openshift-sdn":["10.217.1.74","10.217.1.72"],"openstack/storage":["172.18.0.32","172.18.0.30"]}   True     Setup complete
cinder-volume-lvm-nvme-tcp …
```

Fix NetworkAttachments on Cinder Volume

---

controllers/cinder_controller.go
go.mod
go.sum

The lib-common/modules/database is moved to mariadb-operator/api to remove a circular dependency.

Use database helpers from mariadb-operator/api

---

controllers/cindervolume_controller.go

When configuring the LVM backend, use the external NAD status to configure the 'target_secondary_ip_addresses' but do NOT configure the primary 'target_ip_address'. This causes the cinder-volume service to fall back to using its 'my_ip' for the primary address, which will be the one assigned to it on the OpenShift SDN.
The reason for doing this is that control plane services such as cinder-backup and glance-api and are unable to reach the LVM iSCSI target on external NAD addresses such as the 'storage' network. They can, however, reach the iSCSI target via the OpenShift SDN.
This is not a perfect solution, but is adequate for a PoC using the LVM backend. EDPM compute nodes will access the iSCSI target via the 'storage' network, and c-bak and g-api will reach it via the OpenShift SDN. This …

Fix LVM iSCSI target IP addresses

---

config/manifests/bases/cinder-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

api/bases/cinder.openstack.org_cinders.yaml
api/v1beta1/cinder_types.go
config/crd/bases/cinder.openstack.org_cinders.yaml
config/rbac/role.yaml
controllers/cinder_controller.go
main.go
templates/cinder/config/00-global-defaults.conf

Jira: [OSP-26501](https://issues.redhat.com//browse/OSP-26501)

Enable caching using memcached

---

controllers/cinder_controller.go
test/functional/cinder_controller_test.go

The `DeploymentReadyCondition` condition in the Cinder controller is initialized but then never used.  It doesn't interfere with the overall "ready" state calculation because of the way the `Cinder` CRD's `IsReady()` function is written.  But if it isn't used, we should just drop it.

Remove unused 'DeploymentReady' condition from Cinder status

---

templates/cinder/config/00-global-defaults.conf

Add the [barbican] settings so that all cinder services can access barbican via its internal endpoint. Barbican is already the default key manager.
Jira: [OSPRH-1376](https://issues.redhat.com//browse/OSPRH-1376)

Configure barbican access

---

pkg/cinderapi/deployment.go
test/kuttl/common/assert_sample_deployment.yaml

As noticed in other operators, the -log sidecar ignores SIGTERM on delete. This patch moves the cinder-operator to the dumb-init usage to make sure the SIGTERM is handled properly by the sidecar.
Fixes: [OSPRH-770](https://issues.redhat.com//browse/OSPRH-770)

Move -log sidecar container to dumb-init

---

config/rbac/role.yaml
controllers/cinderapi_controller.go
pkg/cinderapi/statefuleset.go
test/functional/cinder_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml

Change cinder-api from a deployment to a statefulset. Although the service doesn't require preserving stateful data, it helps with the pod naming convention so they're similar to glance-api pods, and eliminates the squirrely suffixes like "cinder-api-xzkpl"

Switch cinder-api to a statefulset

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
main.go
test/functional/suite_test.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-04T16:06:31+03:00       INFO    Controllers.CinderAPI   Reconciled Service 'cinder-api' successfully    {"controller": "cinderapi", "controllerGroup": "cinder.openstack.org", "controllerKind": "CinderAPI", "CinderAPI": {"name":"cinder-api","namespace":"openstack"}, "namespace": "openstack", "name": "cinder-api", "reconcileID": "09fed477-8ad5-4186-8b20-790f409de78a"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.

switch to structured logging

---

config/samples/backends/ceph/kustomization.yaml
config/samples/backends/hpe/3par/fc/kustomization.yaml
config/samples/backends/hpe/3par/iscsi/kustomization.yaml
config/samples/backends/lvm/iscsi/kustomization.yaml
config/samples/backends/lvm/nvme-tcp/kustomization.yaml
config/samples/backends/netapp/ontap/fc/kustomization.yaml
config/samples/backends/netapp/ontap/iscsi/kustomization.yaml
config/samples/backends/netapp/ontap/nfs/kustomization.yaml
config/samples/backends/nfs/kustomization.yaml
config/samples/backends/pure/fc/kustomization.yaml
config/samples/backends/pure/iscsi/kustomization.yaml
config/samples/backends/pure/nvme-roce/kustomization.yaml

Our backend samples no longer work on OCP 4.14 and they fail the `oc kustomize` call with:
error: invalid Kustomization: json: cannot unmarshal string into Go
struct field Kustomization.patches of type types.Patch
In this patch we update the `patches` section from:
```
patches:
- backend
```
to
```
patches:
- path: backend
```

Fix our backend samples

---

Makefile

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk
update to 1.31 version

update operator-sdk to local bin

---

templates/cinderapi/config/01-service-defaults.conf

This patch enables SRBAC by default instead of requiring explicit enabling like we did in OSP17.
Only the API service will include the configuration since policies are to be checked at the endpoint in Cinder API.
Jira: [OSPRH-3281](https://issues.redhat.com//browse/OSPRH-3281)

Enable SRBAC by default

---

api/v1beta1/cinder_webhook.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
pkg/cinder/funcs.go
pkg/cinderapi/const.go
pkg/cinderapi/statefuleset.go
pkg/cinderbackup/const.go
pkg/cinderbackup/statefulset.go
pkg/cinderscheduler/const.go
pkg/cinderscheduler/statefulset.go
pkg/cindervolume/const.go
pkg/cindervolume/statefulset.go
test/kuttl/common/assert_sample_deployment.yaml

Pod affinity is actually an anti-affinity rule intended to spread pods across all OCP workers. However, we don't want this rule to apply to all cinder pods in general. The anti-affinity rule now applies to each specific cinder service (api, scheduler, volume and backup).

Set pod affinity to spread services across OCP workers

---

config/samples/backends/bases/iscsid/iscsid.yaml
config/samples/backends/bases/lvm/lvm.yaml
config/samples/backends/bases/multipathd/multipathd.yaml
config/samples/backends/bases/nvmeof/nvme-fabrics.yaml

The current samples are deploying MachineConfigs on master nodes, which works just fine because right now all our master nodes are also worker nodes, but is not technically correct.
This patch updates the MachineConfigs to deploy on worker nodes, which is the technically correct location.

Backend Samples: place on worker nodes

---

config/samples/backends/bases/iscsid/iscsid.yaml
config/samples/backends/bases/lvm/lvm.yaml
config/samples/backends/bases/multipathd/multipathd.yaml
config/samples/backends/bases/nvmeof/nvme-fabrics.yaml

This reverts commit 9ef753e8bc1f27c7f1a4bcd7dc58255e1c62c787, where we tried to pin the `MachineConfig` to the `worker` role, because they don't work.
Even if the OpenShift CRC node has both master and worker roles, that doesn't mean that we can use them for the `MachineConfig`, because the thing that ties together a `MachineConfig` to a `Machine` is the `MachineConfigPool` and a `Machine` can only belong to one `MachineConfigPool`.
And looking at the available `Machine` in a CRC deployment we see that it has the master role.
```
Name:         crc-ksq4m-master-0
Namespace:    openshift-machine-api
Labels:       machine.openshift.io/cluster-api-cluster=crc-ksq4m
machine.openshift.io/cluster-api-machine-role=master
machine.openshift.io/cluster-api-machine-type=master
```
And looking at the …

Revert "Backend Samples: place on worker nodes"

---

templates/cinder/config/00-global-defaults.conf

This patch updates our global default configuration that had a TODO for the cinder notifications to explicitly state that it is disabled by default and that it's very easy to enable it.
This is an excerpt of what a human operator would need to add to enable it:
```
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
spec:
cinder:
customServiceConfig: |
[oslo_messaging_notifications]
driver = messagingv2
transport_url = {{ .TransportURL }}
```
Jira: #[OSPRH-1613](https://issues.redhat.com//browse/OSPRH-1613)

Remove notifications TODO

---

controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
pkg/cinder/funcs.go

Add a hash of a service's Spec.NodeSelector to the inputs that determine when the corresponding pod should be recreated. This ensures pods are restarted whenever the NodeSelector is modified.

Restart services when their NodeSelector changes

---

config/samples/backends/bases/lvm/lvm.yaml
config/samples/backends/lvm/README.md
config/samples/backends/lvm/iscsi/backend.yaml
config/samples/backends/lvm/nvme-tcp/backend.yaml
controllers/cindervolume_controller.go

With this PR we complete the LVM support in cinder.
We revert the workaround we had for LVM where we would use the OCP
internal network to be able to access from other pods in the same node
since now we can achieve something better easily during the deployment
by changing how we deploy the operators:
```
cd ~/install_yamls
NETWORK_STORAGE_MACVLAN=true make openstack
```
This PR also changes the LVM samples so that they can be used in a real
deployments with 3 nodes.
This is done by labeling one of the nodes as the destination for the LVM
backend.
Related `install_yamls` PR: https://github.com/openstack-k8s-operators/install_yamls/pull/731

Support LVM

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/go.mod
api/go.sum
api/v1beta1/common_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml
config/samples/cinder_v1beta1_cinder.yaml
config/samples/cinder_v1beta1_cinder_tls.yaml
controllers/cinder_controller.go
go.mod
go.sum
test/functional/cinder_controller_test.go
test/functional/cinder_test_data.go
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/assert_tls_sample_deployment.yaml

This moves cinder to fully use MariaDBAccount based on the dev work being done for mariadb-operator:
https://github.com/openstack-k8s-operators/mariadb-operator/pull/184/files
Lead Jira: [OSPRH-4095](https://issues.redhat.com/browse/OSPRH-4095)
1. [x] controller calls EnsureMariaDBAccount up front to make sure MariaDBAccount is present
2. [x] error code from EnsureMariaDBAccount is handled, Conditions are amended when error is returned
3. [x] controller calls NewDatabaseForAccount instead of NewDatabase
4. [x]  GetAccountAndSecret is used to retrieve account /secret to populate template
5. [x]  GetDatabaseByName() , normally used for delete finalizers, replaced with GetDatabaseByNameAndAccount
6. [x]  CreateOrPatchAll() used to patch the Database, replacing CreateOrPatchDB / …

migrate from databaseUsername to databaseAccount and fully use MariaDBAccount

---

pkg/cinderapi/statefuleset.go
test/kuttl/common/assert_sample_deployment.yaml

With the default PodManagementPolicy: OrderedReadyPodManagement the statefulset controller will only progress pods when the previous/current pod is ready or terminated.
When service configuration changes while the pod is starting and the new configuration requires e.g. additional volume mounts the initial pod will never reach ready and therefore an update won't happen.
With ParallelPodManagement the statefulset controller will not wait for pods to be ready or complete termination.

Use PodManagementPolicy: appsv1.ParallelPodManagement for cinder api statefulset

---

controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
pkg/cinder/funcs.go

This reverts commit df33f3ef495813f393a1cc9fc18555118463b9a1.
PR #353 was thought to be the solution to a problem observed while testing updates to how we manage cinder's LVM backend. This pertained to the use of a nodeSelector label that pins the c-vol pod to the k8s node where the LVM backend data is stored. Unfortunately, two subsequent issues were uncovered.
First, the nodeSelector already affects a service's statefulset, which in turn causes pods to be restarted automatically, There's no need to add the nodeSelector to the collection of hashes we use to restart pods when their configuration changes.
Second, the actual problem scenario we hoped to solve was getting a pod to be recreated when it got stuck in the Pending state due to a bad nodeSelector value. Currently we use an …

Revert "Restart services when their NodeSelector changes"

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
test/functional/cinder_controller_test.go

The way cinder-operator is handling conditions is not correct.
In this PR we make all necessary changes so that it behaves like
the minor update code expects and how a human operator would expect.
At the beginning of the reconcile we should always set all conditions to
Unknown to make sure that they are reset to the real status.
This is the right thing to do because we are doing the steps
sequentially, so any step we don't reach, we don't know its status,
hence the "Unknown" status condition.
Fix the global "Ready" condition for Cinder CRs so that it's only set to
"True" when we have gone through all the steps and not just based on the
current value.
The patch also set the global "Ready" condition to False instead of to
Unknown, as that's the case unless proven otherwise by reaching the …

Fix Conditions

---

api/go.mod
api/go.sum
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
go.mod
go.sum
pkg/cinder/funcs.go

Do not update a condition's LastTransitionTime unless its state actually changes. This ensures the LastTransitionTime isn't always modified during every reconcilation. PR #364 reinitializes all all conditions to Unknown prior to determining their actual state, and the intent is to avoid modifying the LastTransitionTime unless reconciliation modifies the condition's state.
Jira: [OSPRH-5698](https://issues.redhat.com//browse/OSPRH-5698)
NOTE: If other operators want to adopt this pattern, then the cinder.SaveConditions() and cinder.RestoreLastTransitionTimes() functions should move to lib-common.

Fix updates to a condition's LastTransitionTime

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

Initialize the ReadyCondition to Unknown, and in the controller's defer function mirror the latest current condition. The updates the ReadyCondition with information about whatever condition is not yet ready.

Mirror ReadyCondition with the actual current condition

---

README.md
config/samples/backends/ceph/backend.yaml
config/samples/backends/netapp/ontap/nfs/backend.yaml
config/samples/backends/netapp/ontap/nfs/cinder-volume-ontap-secrets.yaml
config/samples/backends/nfs/backend.yaml
config/samples/backends/nfs/cinder-volume-nfs-secrets.yaml

Update extraMounts for mounting ceph client files to use the 'secret' volume type instead of 'projected'. The projected volume type is meant for situations where there are multiple sources that need to all be merged, but with ceph there's just a single source.
Update the NFS and Netapp's ontap NFS configurations to switch from using a shares-config file to using the driver's nas_host and nas_share_patch config options. The shares-config file is not considered best practice for situations where multiple shares need to be configured. Instead, it's better to configure multiple backends, one per share, so that all volume requests go through the scheduler.
The NFS configurations also now include a few more recommended settings:
nfs_snapshot_support=true
nas_secure_file_operations=false …

Update some backend samples

---

.pre-commit-config.yaml
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
main.go
pkg/cindervolume/volumes.go
test/functional/base_test.go
test/functional/cinder_controller_test.go
test/functional/suite_test.go

* removed unused func params
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* various small style fixes found by the linter

Ensure golangci-lint runs on all files

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

In this PR we fix the cinder operator to follow the latest recommendations on how to handle the status conditions of the CRDs.
At a high level the changes are:
- All CRDs have an `ObservedGeneration` field
- `ObservedGeneration` is updated with the `Generation` field value set by OpenShift as soon as the status conditions are initialized to `Unknown` in the beginning of the reconciliation.
- Top level `Cinder` CRD only considers sub CRDs to have valid data when their `Generation` and `ObservedGeneration` fields match.
- All controllers take into account their `ObservedGeneration` field to determine whether they are ready or not.

Fixing conditions

---

README.md
docs/additional_network.md
docs/api_isolated_network.md
docs/ceph_backend.md

Our current README.md file does not provide a quick guide to start paying with OpenStack and a Cinder backend.
In this patch we update the README.md to present a quick starting guide that deploys OpenStack with LVM as a block device backend.
It also moves a number of sections to their own independent files as a cleanup of the top level README.

README cleanup

---

api/go.mod
api/go.sum
api/v1beta1/cinder_webhook.go
go.mod
go.sum
test/functional/cinder_controller_test.go

Can also be called from the openstack-operator webhook on the CinderSpecCore, like for other operators in [1].
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/d2703d3a321c979dacaca95b5d4a634bf116e0db/apis/core/v1beta1/openstackcontrolplane_webhook.go#L181

Add webhook to validate service override endpoint type

---

templates/cinder/config/00-global-defaults.conf

Because we deploy the database in multi-master mode we can have cases where a service writes something in the database and when another one reads from the DB that data is not yet there.
This is very problematic, because all the cinder code assumes that that can never happen.
For example we've seen in CI jobs the following behavior:
- Cinder api creates a worker registry in the DB when deleting a volume on DB node 1.
- Cinder api makes an RPC call to cinder-volume to delete the volume.
- Cinder volume tries to read the worker registry from DB node 2 but the data is not there yet, so it misbehaves.
In this patch we change the default value on the DB engine of not waiting for writes to wait on read, update, and insert.
This will have a performance impact, but the alternative is for cinder to …

Wait for DB writes to propagate (causality checks)

---

templates/cinder/config/00-global-defaults.conf

On PR 392 we changed to waiting on writes for updates and inserts, but upon further analysis we have decided that just doing it for reads should be enough, as the order of the updates will be reconciled automatically by the DB engine.
In this patch we change the value of `mysql_wsrep_sync_wait` to 1 to only wait on reads.

Wait for DB writes only on reads (causality checks)

---

templates/cinder/config/00-global-defaults.conf

Configure cinder's storage_availability_zone but leave the default_availability_zone unset so that the user can override the default "nova" value using either parameter.
For background, cinder has separate default_availability_zone and storage_availability_zone parameters, and the former supersedes the latter. If the default_availability_zone is unset, cinder will fallback to the storage_availability_zone. So, if the cinder operator configures the default_availability_zone then a cloud admin would be unable to override it with the
storage_availability_zone parameter. Historically, tripleo only configured the storage_availability_zone.

Do not configure cinder's default_availability_zone

---

config/samples/backends/bases/iscsid/iscsid.yaml

This patch changes the time to fail an iSCSI login request in our samples.
The default is 8 retries and 15 seconds for each one, so 120 seconds in total.
This patch changes the OpenShift cluster default to 3 retries and 5 seconds each (15 seconds in total), which is convenient for testing, as any healthy deployment and backend should be able to login to the backend in that amount of time, and if there is a broken path it will not take 2 minutes to give up.
Jira: https://issues.redhat.com/browse/OSPRH-7393
Jira: https://issues.redhat.com/browse/OSPRH-7415

Samples: iscsid login timeout

---

api/bases/cinder.openstack.org_cinders.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinder_webhook.go
config/crd/bases/cinder.openstack.org_cinders.yaml
controllers/cinder_controller.go
templates/cinder/config/00-global-defaults.conf
templates/cinder/config/10-cinder_wsgi.conf

Multiple limitations exist with existing code:
- Human operator cannot configure Apache Timeout, so it's fixed at the defaults of 60 seconds.
This can be problematic for cinder backends that under load can take longer on the export and mapping.
- Default HAProxy timeout is 30 seconds, which is different than the default in OSP17 (60 seconds)
- Human operators would need to sync values between 3 places: HAProxy, Apache, oslo.messaging sync RPC (call).
This patch adds an `apiTimeout` field to the `CinderSpecBase` to allow human operators to simultaneously configure the timeouts for HAProxy, Apache, and the `rpc_response_timeout`.
The `apiTimeout` defaults to 60 seconds, to mimic the behavior present in OSP17.
Having different timeouts for HAProxy, Apache, and `rpc_response_timeout` is …

Add configurable API Timeouts

---

api/v1beta1/cinder_types.go
api/v1beta1/cinder_webhook.go

Kubebuilder doesn't always set the default of APITimeout, so with this patch we ensure that APITimeout field always has a valid value.

Set APITimeout defaults on the webhook

---

controllers/cinder_controller.go

Current code names the database for cinder based on the Cinder CR name, and this is ok if the instance is called cinder, but if the name is something like "mycloud-cinder" then the database creation doesn't work as it fails with:
```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax;
check the manual that corresponds to your MariaDB server version for
the right syntax to use near '-cinder' at line 1
```
We have a constant called `DatabaseName` that contains the name that we should be using for the database creation, and this patch uses it.
Jira: [OSPRH-7396](https://issues.redhat.com//browse/OSPRH-7396)

Always name database "cinder"

---

templates/cinder/config/00-global-defaults.conf

The openstack-k8s-operators/mariadb-operator#229 switched the mariadb-operator to deploy in Active/Passive mode per default, instead of multimaster.

Revert mysql wsrep sync wait

---

api/v1beta1/cindervolume_types.go
controllers/cinder_controller.go
controllers/cindervolume_controller.go
pkg/cindervolume/const.go
test/functional/cinder_controller_test.go
test/functional/cinder_test_data.go
test/functional/suite_test.go

When the Cinder CR is created using a name that is not "cinder" the `backend` label in the StatefulSet and the final cinder volume Pod will have the wrong value.
This is because the code that determines the backend name in the cinder volume controller doesn't have access to the actual name, so it tries to figure it out from the name of the CinderVolume CR, but since the name no longer starts with `cinder-volume`, then the value is wrong.
This patch changes the way we do this, and now the cinder-operator adds a label to the CinderVolume CR with the name of the backend, then the cinder volume controller uses it to pass it to the statefulset .
Jira: [OSPRH-7396](https://issues.redhat.com//browse/OSPRH-7396)

Fix backend label when using non cinder name

---

templates/cinder/config/cinder-backup-config.json
templates/cinder/config/cinder-volume-config.json
templates/cinder/config/cinder-volume-lvm-config.json

Just like with iscsiadm and other command tools there is a need to run the command on the host's namespace.
If we don't run it like that the command will get stuck in:
```
cryptsetup luksOpen --key-file=- /dev/dm-8 crypt-os-brick+dev+dm-8
```
And if we manually run the command with debug option (`--debug --verbose`) we'll see that it gets stuck in:
```
```
And is unable to continue with the rest:
```
Command successful.
```
This patch ensure we use `nsenter` to run `cryptsetup`.

Fix attaching encrypted volume on controller nodes

---

docs/ceph_backend.md

The yaml block was not formatted within ```example``` causing it to be formatted as a paragraph in a single line.

Correct formatting of ceph doc

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler

Return nil error in case NotFound and to use RequeueAfter

---

test/functional/cinder_controller_test.go

As done for manila, we're not really interested in the `ErrorReason` in functional tests as we depends on what is provided by `lib-common`. However, We still want to match the resulting condition boolean.
This patch removes the `TLSInput` `error message` so we don't fail if something changes in `lib-common`.

Remove errorReason from tls input check functional test

---

controllers/cinder_common.go
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
pkg/cinder/const.go

This PR consists of 3 commits:
1. Steals a commit from the not-yet-merged PR #365, which defines variables for durations and requeue. The other PR needs to be rebased, and that commit can be dropped if this patch merges first.
2. A new verifyServiceSecret() function ensures cinder services don't get restarted when something unrelated in the ctlplane secret changes.
3. A new verifyConfigSecrets() function consolidates code that records the hash of the TransportURL secret and various service configuration secrets.
See also https://github.com/openstack-k8s-operators/manila-operator/pull/324

Move to VerifySecret when checking the ctlplane secret, and other code consolidation

---

config/samples/backends/README.md
config/samples/backends/hpe/3par/fc/backend.yaml
config/samples/backends/hpe/3par/fc/custom-container.yaml
config/samples/backends/hpe/3par/fc/kustomization.yaml
config/samples/backends/hpe/3par/iscsi/backend.yaml
config/samples/backends/hpe/3par/iscsi/custom-container.yaml
config/samples/backends/hpe/3par/iscsi/kustomization.yaml
config/samples/backends/pure/fc/backend.yaml
config/samples/backends/pure/fc/custom-container.yaml
config/samples/backends/pure/fc/kustomization.yaml
config/samples/backends/pure/iscsi/backend.yaml
config/samples/backends/pure/iscsi/custom-container.yaml
config/samples/backends/pure/iscsi/kustomization.yaml
config/samples/backends/pure/nvme-roce/backend.yaml
config/samples/backends/pure/nvme-roce/custom-container.yaml
config/samples/backends/pure/nvme-roce/kustomization.yaml

Te way custom images are specified has changed, and now it no longer uses the `containerImage` file in the cinder sections but instead needs to be specified in the `OpenStackVersion`.
This patch updates the examples to match the latest code.

Update backend samples using custom images

---

controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

config/samples/backends/bases/nvmeof/fix-ocp-nvme.yaml
config/samples/backends/bases/nvmeof/kustomization.yaml

OpenShift image has the NVMe `hostid` and `hostnqn` hardcoded, so it ends up being the same in all the control plane nodes, which is problematic.
This `MachineConfig` fixes this issue by recreating both files when the `hostid` doesn't match the system-uuid of the machine it is running on.
Bugs:
- https://issues.redhat.com/browse/OCPBUGS-34629
- https://github.com/openshift/os/issues/1519
- https://github.com/openshift/os/pull/1520

NVMe sample: Fix nvme ids

---

README.md
docs/user-guide/cinder.md
docs/user-guide/commonalities.md
docs/user-guide/index.md

This PR adds documentation to explain concepts needed to understand the configuration of the Block Storage (cinder) service on OpenShift.
There is general information meant for users explaining extra volumes, placement restrictions, snippets, etc., as well as cinder specific topics.

Docs: Add generic guide

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

This is an updated version of Gorka's PR #365. In addition to rebasing, it drops one commit that's no longer required (the change was made in another PR).

Improve logs

---

api/go.mod
api/go.sum
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
go.mod
go.sum

For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.
Jira: https://issues.redhat.com/browse/OSPRH-8680
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579

Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

---

api/v1beta1/cinder_types.go
api/v1beta1/common_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/cinder_controller.go
pkg/cinder/cronjob.go
pkg/cinder/dbsync.go
pkg/cinderapi/statefuleset.go
pkg/cinderbackup/statefulset.go
pkg/cinderscheduler/statefulset.go
pkg/cindervolume/statefulset.go
test/functional/base_test.go
test/functional/cinder_controller_test.go
test/functional/cinder_test_data.go

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

pkg/cinderapi/statefuleset.go
pkg/cinderbackup/statefulset.go
pkg/cinderscheduler/statefulset.go
pkg/cindervolume/statefulset.go
templates/cinder/config/cinder-api-config.json
templates/cinder/config/httpd.conf
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/assert_tls_sample_deployment.yaml

Run all cinder services as the cinder user instead of root.
This updates our kolla usage and apache configs to work in this configuration.
Jira: https://issues.redhat.com/browse/OSPRH-10083

Run cinder services as cinder user

---

kuttl-test.yaml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Add KUTTL and tempest zuul jobs (meant to replace the prow ones in the long term)
KUTTL: generate JUnitXML reports
- switch the type to XML (the accepted value is 'xml' lowercase, not uppercase);
- tune the name a bit to highlight it is a report;
- add the new reportGranularity parameter which is supported by kuttl 0.20.0 and will restore the pre-1.17 JUnitXML format (granularity by test case, instead of by step).
- remove the URL of kuttl, so that it is not tied to a specific release.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2628

 More zuul jobs, and generate JUnitXML reports for KUTTL

---

test/functional/base_test.go
test/functional/cinder_controller_test.go
test/functional/cinder_test_data.go

This change adds a functional test for `Cinder` `extraMounts`. It ensures we're able to validate the abstraction of `corev1.VolumeSource` struct introduced in `lib-common/storage` module.
Jira: https://issues.redhat.com/browse/OSPRH-11210

Add extraMounts functional tests

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except when Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16975](https://issues.redhat.com//browse/OSPRH-16975)

Do not update status when reconciler exits due to panic

---

controllers/cinder_controller.go
go.mod
go.sum
test/functional/cinder_controller_test.go

Adds watches of the Nova controller on the KeystoneAPI status to reconcile if e.g. the endpoint list changes. This triggers setting the new KeystoneAuthURL on the sub components to update their configuration.
Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/591
Jira: [OSPRH-16994](https://issues.redhat.com//browse/OSPRH-16994)

Watch KeystoneAPI status updates to reconcile

---

pkg/cinder/volumes.go
test/functional/cinder_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/assert_tls_sample_deployment.yaml

`Cinder` `Pods` shouldn't inherit `/etc/localtime` from the worker node/host where the `Pod` is scheduled. Mounting that volume has several drawbacks, and one of them is having these Pods not aligned with the rest of the control plane other than establish a dependency with the underlying host.
It results difficult to track requests in case of troubleshooting and as per [1] the current approach is not recommended.
Because there is no reason to modify `localtime` to match the underlying host, this patch fixes the reported bug by removing it.
Jira: https://issues.redhat.com/browse/OSPRH-17676
[1] https://access.redhat.com/solutions/5487331

Remove localtime hostMount

---

controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

This change uses GetLogger instead of direct use of log.FromContext to support structured logging.

Use strucutred logging

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinder_types.go
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
test/functional/cinder_controller_test.go

`Nova` and probably other operators have `notificationsBus` instead of `notificationBus`, which let storage operator to slightly diverge due to the missing final `s`.
This patch fixes the interface (currently present only in main).

Fix notificationsBusInstance typo in the API parameter
