openstack-k8s-operators/cinder-operator

config/rbac/role.yaml
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

Add missing patch permissions for several resource types

Add missing patch perms

---

controllers/cinderapi_controller.go

As we've done in [0], it's a good idea using keystone to get the existing service spec instead
of explicitly building an object. This patch simplifies the logic in the `reconcileDelete` flow.
[0] https://github.com/openstack-k8s-operators/glance-operator/pull/31
Signed-off-by: Francesco Pantano <fpantano@redhat.com>

Get Service by name using keystone

---

controllers/cinderapi_controller.go

We need to make sure that the finalizer is removed from the CinderAPI CR regardless of what the current state of Cinder is within Keystone

Always attempt to remove finalizer on delete

---

controllers/cinderapi_controller.go

To cleanup the created resources it is ok to just remove the finalizer which gets set during create. When the owner gets deleted and the owning resource removes the finalizer. k8s does does the cleanup of those resources where the owner is missing and the relevant CR controller calls the cleanup actions, if any.

Simplify resource cleanup

---

OWNERS

This patch adds Alan, Eric, and Gorka to the OWNERS files.

Add Storage folks to OWNERS file

---

api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
api/v1beta1/cinderapi_types.go
api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml
config/samples/cinder_v1beta1_cinder.yaml

This chnage makes the container image optional and
updates the defaults to use stable/zed images.

use stable/zed container images

---

controllers/cinder_controller.go

We are currently watching `Secret`s in the Cinder controller, but we do not create any `Secret`s of our own, so it does nothing.  What we are trying to do is watch the derivative `Secret` created by the `TransportURL` that we create.  Using a watch function instead of `Owns()` will allow us to properly watch those derivative `Secret`s.

Properly watch TransportURL secrets

---

.github/create_bundle.sh
.pre-commit-config.yaml
Makefile
templates/cinder/bin/init.sh
templates/common/common.sh

This patch also adds bashate hook in pre-commit.

Update pre-commit hook with golangci-lint

---

api/v1beta1/cinderbackup_types.go
api/v1beta1/cinderscheduler_types.go
api/v1beta1/cindervolume_types.go

These were missed in an earlier patch.

Add missing omitempty tag to slices

---

controllers/cinder_controller.go

When an entry in the CinderVolumes spec is deleted, the corresponding cinder-volume deployment (i.e. the c-vol backend) must also be deleted. This is done by scanning the list of cinder-volume deployments, and deleting them if their name doesn't appear in the CinderVolumes spec.
Note that removing the cinder-volume backend currently does not clean up the service entry in the cinder DB. That will be handled in a follow-up patch.

Clean up cinder-volume deployments

---

controllers/cinder_controller.go

We recently added labels to ConfigMaps and other service resources, but we didn't add them to the `TransportURL`.
This patch adds the `service=cinder` label to the `TransportURL` that is missing it.

Add label to TransportURL

---

docs/dev/design-decisions.md

This PR adds a simple document describing some of the design decisions taken in the project.
This initial patch doesn't intend to be a complete list, just a start with some of these decisions.

Docs: Add design decisions

---

api/bases/cinder.openstack.org_cinders.yaml
api/v1beta1/cinder_types.go
config/crd/bases/cinder.openstack.org_cinders.yaml
controllers/cinder_controller.go

Jira: [OSPRH-5919](https://issues.redhat.com//browse/OSPRH-5919)

Add Status.ObservedGeneration to Cinder CR

---

config/manifests/bases/cinder-operator.clusterserviceversion.yaml

Implements: [OSPRH-7947](https://issues.redhat.com//browse/OSPRH-7947)

Add Required Infrastructure Annotations to CSV

---

config/rbac/role.yaml
controllers/cinder_controller.go
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go

We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363

Adding patch rbac perm for serviceaccounts

---

api/go.mod
api/go.sum
controllers/cinderapi_controller.go
controllers/cinderbackup_controller.go
controllers/cinderscheduler_controller.go
controllers/cindervolume_controller.go
go.mod
go.sum

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/559
Jira: [OSPRH-9991](https://issues.redhat.com//browse/OSPRH-9991)

Update tls cert secret validation due VerifyCertSecrets() change

---

test/functional/cinder_controller_test.go

Related: [OSPRH-14494](https://issues.redhat.com//browse/OSPRH-14494)

[functional] verify LastAppliedTopology != nil before checking name

---

test/functional/base_test.go
test/functional/cinder_controller_test.go

This patch improves our topology testing with several enhancements and extends the `topologyRef` tests:
- `finalizer` verification for each sub component that references a topology
- Updated `Topologies` to support `component-specific` label selectors
This work completes the topology validation improvements initiated in [1], addressing the remaining open points.
Jira: https://issues.redhat.com/browse/OSPRH-15220
[1] nova-operator#941

Improve topology testing coverage

---

controllers/cinder_controller.go

We currently assign to the `subCR` spec a `memcached` instance under certain conditions.
We observe a `panic` for the `subcontrollers` (`api/scheduler/backup/volumes`) on [1] (the same applies to sched and volumes) when it tries to dereference a field that is a `nil` pointer, and this let the operator crash without any chance to recover. 
Regardless of the `memcached` CR config (`TLS` or not), we always wait in the main controller for it to be ready, and only then we unblock the rest of the reconciliation loop.
For this reason, we can always assign to the underlying components the `MemcachedInstance` defined at the top-level because:
1. we know it exists
2. we need to pass it down to the `StatefulSet` and we do not support a different `memcached` instance per component (we only support …

Fix panic due to missing memcachedInstance in the subCR

---

Makefile
api/bases/cinder.openstack.org_cinderapis.yaml
api/bases/cinder.openstack.org_cinderbackups.yaml
api/bases/cinder.openstack.org_cinders.yaml
api/bases/cinder.openstack.org_cinderschedulers.yaml
api/bases/cinder.openstack.org_cindervolumes.yaml
config/crd/bases/cinder.openstack.org_cinderapis.yaml
config/crd/bases/cinder.openstack.org_cinderbackups.yaml
config/crd/bases/cinder.openstack.org_cinders.yaml
config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
config/crd/bases/cinder.openstack.org_cindervolumes.yaml

Jira: [OSPRH-17807](https://issues.redhat.com//browse/OSPRH-17807)

Enable CRD descriptions
